system:
  name: db-service
  port: 9000

registry:
  host: 127.0.0.1
  port: 8500

mysql:
  host: 101.33.196.35
  port: 3306
  db: oj_online_server
  user: root
  password: 1225pdhGkl

redis:
  host: 127.0.0.1
  port: 6379

log:
  path: "../log"
  level: debug
