version: '3'

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1

services:
  consul-server-01:
    image: consul:latest
    container_name: consul-server-01
    command: "agent -server -client=0.0.0.0 -node=consul01 -ui -bootstrap-expect=3"
    restart: always
    volumes:
      - /root/server/Oj-Online-Server/consul-server-data/:/consul/data
    networks:
      - net
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"

  consul-server-02:
    image: consul:latest
    container_name: consul-server-02
    command: "agent -server -client=0.0.0.0 -node=consul02 -ui"
    restart: always
    volumes:
      - /root/server/Oj-Online-Server/consul-server-data/:/consul/data
    networks:
      - net
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"

  consul-server-03:
    image: consul:latest
    container_name: consul-server-03
    command: "agent -server -client=0.0.0.0 -node=consul03 -ui"
    restart: always
    volumes:
      - /root/server/Oj-Online-Server/consul-server-data/:/consul/data
    networks:
      - net
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"

  consul-client:
    image: consul:latest
    container_name: consul-client
    command: "agent -client -node=client"
    restart: always
    networks:
      - net
