version: '3'

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1

services:
  consul-server1:
    image: hashicorp/consul:1.11.2
    container_name: consul-server1
    restart: always
    volumes:
      - ./server1.json:/consul/config/server1.json:ro
      - ./certs/:/consul/config/certs/:ro
    networks:
      - net
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent -bootstrap-expect=3"

  consul-server2:
    image: hashicorp/consul:1.11.2
    container_name: consul-server2
    restart: always
    volumes:
      - ./server2.json:/consul/config/server2.json:ro
      - ./certs/:/consul/config/certs/:ro
    networks:
      - net
    command: "agent -bootstrap-expect=3"

  consul-server3:
    image: hashicorp/consul:1.11.2
    container_name: consul-server3
    restart: always
    volumes:
      - ./server3.json:/consul/config/server3.json:ro
      - ./certs/:/consul/config/certs/:ro
    networks:
      - net
    command: "agent -bootstrap-expect=3"

  consul-client:
    image: hashicorp/consul:1.11.2
    container_name: consul-client
    restart: always
    volumes:
      - ./client.json:/consul/config/client.json:ro
      - ./certs/:/consul/config/certs/:ro
    networks:
      - net
    command: agent

  rabbitmq:
    image: rabbitmq:3.8.16-management
    container_name: my-rabbit
    restart: always
    hostname: rabbitServer # 节点名 rabbit@rabbitServer，不然会取容器ID
    environment:
      RABBITMQ_DEFAULT_USER: oj # 用户名
      RABBITMQ_DEFAULT_PASS: 1225 # 密码
      RABBITMQ_DEFAULT_VHOST: '/oj'  # 虚拟主机
      RABBITMQ_PLUGINS_DIR: '/plugins:/myplugins' # 插件目录
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./data:/var/lib/rabbitmq
      - ./myplugins:/myplugins
    networks:
      - net