version: '3'

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1

services:
  db-service:
    container_name: db-service
    privileged: true
    build:
      context: ./db-service # 路径
      dockerfile: Dockerfile
    volumes:
      - /root/server/Oj-Online-Server/oj-online-backend/log:/app/log
    ports:
      - "9000"
    networks:
      - net

  judge-service:
    container_name: judge-service
    privileged: true
    build:
      context: ./judge-service
      dockerfile: Dockerfile
    volumes:
      - /root/server/Oj-Online-Server/oj-online-backend/log:/app/log
    ports:
      - "9020:9020"
    networks:
      - net
    depends_on: # 本地服务的依赖，控制启动先后顺序
      - db-service
  
  question-service:
    container_name: question-service
    privileged: true
    build:
      context: ./question-service
      dockerfile: Dockerfile
    volumes:
      - /root/server/Oj-Online-Server/oj-online-backend/log:/app/log
    ports:
      - "9010"
    networks:
      - net
    depends_on: # 本地服务的依赖，控制启动先后顺序
      - db-service
      - judge-service
