version: '3'

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1

services:
  consul-dev:
    image: consul:1.15.4
    container_name: consul-dev
    command: "agent -dev -client=0.0.0.0 -node=dev"
    restart: always
    networks:
      - net
    ports:
      - "8500:8500"
