system:
  name: question-service
  port: 9010

registry:
  host: 127.0.0.1
  port: 8500

redis:
  ip: 127.0.0.1
  port: 6379

jwt:
  key: 'dAjOs8FF6H^df$BXaY@xG!%#AWMgQRbq'

sms:
  accessKeyId: 'LTAI5tKv69qFhZPXbV6vzFGL'
  accessKeySecret: 'cVwcLxfehs0dTgbhWgMT42L7j2bOz7'
  endpoint: 'dysmsapi.aliyuncs.com'
  signName: 'MessiGVB'
  templateCode: 'SMS_463639205'

log:
  path: "../log"
  level: debug