system:
  name: question-service
  port: 9010

registry:
  host: 101.33.196.35
  port: 8600

redis:
  ip: 10.0.8.10
  port: 6379

jwt:
  key: 'KVAi!%6BRZvT7vwIXZEK3yQsF8FbubkO'

sms:
  accessKeyId: 'LTAI5tKv69qFhZPXbV6vzFGL'
  accessKeySecret: 'cVwcLxfehs0dTgbhWgMT42L7j2bOz7'
  endpoint: 'dysmsapi.aliyuncs.com'
  signName: 'MessiGVB'
  templateCode: 'SMS_463639205'

log:
  path: "/app/log"
  level: info
